[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datetick"
version = "0.9.0"
authors = [
  {name = "Bob Weigel", email = "rweigel@gmu.edu"},
  {name = "Brendan Gallagher"},
]
description = "Sensible date tick locator for matplotlib"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
requires-python = ">=3.7"
dependencies = ["matplotlib", "numpy", "python-dateutil"]

[project.urls]
Homepage = "http://pypi.python.org/pypi/datetick/"

[tool.setuptools.packages.find]
where = ["."]
